### ISSUE TITLE
issue with bindings

### ISSUE THREAD

**Issue by EricBonin** [michelderooij/Remove-MessageClassItems#4]
Hello, there seem to be an issue with the binding with the latest version:
*******************************
PS C:\Script\EWS\Remove-MessageClassItems> .\Remove-MessageClassItems.ps1 -Identity "kevin.bank@xxxxxx.com" -MessageClass "*EnterpriseVault*" -Before ((Get-Date).AddDays(-2)) -WhatIf:$true -verbose
C:\Script\EWS\Remove-MessageClassItems\Remove-MessageClassItems.ps1 : Parameter set cannot be resolved using the
specified named parameters.
At line:1 char:1
+ .\Remove-MessageClassItems.ps1 -Identity "kevin.bank@iqeq.com" -Messa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-MessageClassItems.ps1], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Remove-MessageClassItems.ps1
*******************************

**Comment by michelderooij** [comment]
Specify one of the auth methods or UseDefaultCredentials when operating locally using current context
