### ISSUE TITLE
Error performing operation FindFolders without Search options in . Error: You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by suglasp** [michelderooij/Remove-MessageClassItems#5]
When i try the cmdlet below, I always get the error "Error performing operation FindFolders without Search options in . Error: You cannot call a method on a null-valued expression.".

Even when I leave the -IncludeFolders  or the -ExcludeFolders abscent, it does not work and says the values are null.
Been debugging the script and found something must go wrong in function Process-Mailbox.

`.\Remove-MessageClassItems.ps1 -Identity "someuser" -MessageClass IPM.Note.EnterpriseVault.Shortcut -DeleteMode MoveToDeletedItems -MailboxOnly -Impersonation -UseDefaultCredentials -IncludeFolders @("#Inbox#", "#SentItems#") -ExcludeFolders @("#Calendar#", "#Contacts#", "#DeletedItems#", "#Notes#") -Verbose`

VERBOSE: Module Microsoft.Exchange.WebServices v2.2.1.0 already loaded
VERBOSE: Module Microsoft.Identity.Client v4.25.0.0 already loaded
VERBOSE: Using Default Credentials
VERBOSE: DeleteMode is MoveToDeletedItems
VERBOSE: Removing messages of class IPM.Note.EnterpriseVault.Shortcut
Processing mailbox someuser@somedomain.com (someuser)
VERBOSE: Using someuser@somedomain.com for impersonation
VERBOSE: Looking up EWS URL using Autodiscover for someuser@somedomain.com
VERBOSE: Using EWS endpoint https://autodiscover.somedomain.com/EWS/Exchange.asmx
VERBOSE: Constructing folder matching rules
VERBOSE: Processing primary mailbox someuser@somedomain.com
VERBOSE: Collecting folders containing items to process
**WARNING: Error performing operation FindFolders without Search options in . Error: You cannot call a method on a null-valued expression.**
VERBOSE: Found 0 folders matching folder search criteria
VERBOSE: 0 item(s) processed in 00:00:00 - average 0 items/min
VERBOSE: Processing someuser@somedomain.com finished

Update comment:
Function Process-Mailbox contains the line
$FoldersToProcess= Get-SubFolders -Folder $Folder -CurrentPath '' -IncludeFilter $IncludeFilter -ExcludeFilter $ExcludeFilter -ScanAllFolders $ScanAllFolders -EwsService $EwsService

Get-SubFolders returns no data it seems.

**Comment by michelderooij** [comment]
2.22 fixes the this error

**Comment by suglasp** [comment]
> 2.22 fixes the this error

Okay, I can confirm the problem is fixed.
